Watching for file changes with StatReloader
Bad Request: /accounts/register/
Bad Request: /accounts/register/
"POST /accounts/register/ HTTP/1.1" 400 50
"POST /accounts/register/ HTTP/1.1" 400 50
"OPTIONS /accounts/login/ HTTP/1.1" 200 0
HTTP Error 401: Unauthorized
"POST /accounts/login/ HTTP/1.1" 201 113
HTTP Error 401: Unauthorized
"POST /accounts/login/ HTTP/1.1" 201 113
/home/ubuntu/datahub-api/core/settings.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
June 23, 2022 - 05:53:35
Django version 4.0.5, using settings 'core.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
{'email': 'varun@digitalgreen.org', 'user_otp': '670762', 'otp_count': 1, 'updation_time': datetime.datetime(2022, 6, 23, 5, 53, 35, 746055)}
{'email': 'varun@digitalgreen.org', 'user_otp': '135900', 'otp_count': 1, 'updation_time': datetime.datetime(2022, 6, 23, 5, 53, 35, 746055)}
Watching for file changes with StatReloader
/home/ubuntu/datahub-api/core/settings.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
June 23, 2022 - 06:26:37
Django version 4.0.5, using settings 'core.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Traceback (most recent call last):
  File "/home/ubuntu/datahub-api/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/datahub-api/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/datahub-api/.venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/datahub-api/.venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 386, in execute
    settings.INSTALLED_APPS
  File "/home/ubuntu/datahub-api/.venv/lib/python3.10/site-packages/django/conf/__init__.py", line 87, in __getattr__
    self._setup(name)
  File "/home/ubuntu/datahub-api/.venv/lib/python3.10/site-packages/django/conf/__init__.py", line 74, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ubuntu/datahub-api/.venv/lib/python3.10/site-packages/django/conf/__init__.py", line 183, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/datahub-api/core/settings.py", line 182
    EMAIL_HOST_USER = "farmstack.dg@gmail.com
                      ^
SyntaxError: unterminated string literal (detected at line 182)
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/datahub-api/.venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/ubuntu/datahub-api/.venv/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 158, in inner_run
    run(
  File "/home/ubuntu/datahub-api/.venv/lib/python3.10/site-packages/django/core/servers/basehttp.py", line 236, in run
    httpd = httpd_cls(server_address, WSGIRequestHandler, ipv6=ipv6)
  File "/home/ubuntu/datahub-api/.venv/lib/python3.10/site-packages/django/core/servers/basehttp.py", line 76, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.10/wsgiref/simple_server.py", line 50, in server_bind
    HTTPServer.server_bind(self)
  File "/usr/lib/python3.10/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OverflowError: bind(): port must be 0-65535.
Performing system checks...

System check identified no issues (0 silenced).
June 23, 2022 - 06:30:17
Django version 4.0.5, using settings 'core.settings'
Starting development server at http://0.0.0.0:80000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
"POST /accounts/register/ HTTP/1.1" 201 358
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/otp/ HTTP/1.1" 200 618
"POST /accounts/login/ HTTP/1.1" 201 117
"OPTIONS /accounts/otp/ HTTP/1.1" 200 0
"POST /accounts/otp/ HTTP/1.1" 200 618
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/otp/ HTTP/1.1" 200 618
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/otp/ HTTP/1.1" 200 618
"OPTIONS /accounts/register/eddc9ee1-f3f9-4577-8c53-7553b5cced47/ HTTP/1.1" 200 0
Not Found: /accounts/register/eddc9ee1-f3f9-4577-8c53-7553b5cced47/
Not Found: /accounts/register/eddc9ee1-f3f9-4577-8c53-7553b5cced47/
"PUT /accounts/register/eddc9ee1-f3f9-4577-8c53-7553b5cced47/ HTTP/1.1" 404 23
"PUT /accounts/register/eddc9ee1-f3f9-4577-8c53-7553b5cced47/ HTTP/1.1" 404 23
Not Found: /accounts/register/eddc9ee1-f3f9-4577-8c53-7553b5cced47/
Not Found: /accounts/register/eddc9ee1-f3f9-4577-8c53-7553b5cced47/
"PUT /accounts/register/eddc9ee1-f3f9-4577-8c53-7553b5cced47/ HTTP/1.1" 404 23
"PUT /accounts/register/eddc9ee1-f3f9-4577-8c53-7553b5cced47/ HTTP/1.1" 404 23
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/otp/ HTTP/1.1" 200 618
"POST /accounts/login/ HTTP/1.1" 201 117
Unauthorized: /accounts/otp/
Unauthorized: /accounts/otp/
"POST /accounts/otp/ HTTP/1.1" 401 57
"POST /accounts/otp/ HTTP/1.1" 401 57
"POST /accounts/otp/ HTTP/1.1" 200 618
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/otp/ HTTP/1.1" 200 618
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/otp/ HTTP/1.1" 200 618
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/otp/ HTTP/1.1" 200 618
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/otp/ HTTP/1.1" 200 618
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/otp/ HTTP/1.1" 200 618
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/otp/ HTTP/1.1" 200 618
Bad Request: /accounts/login/
Bad Request: /accounts/login/
"POST /accounts/login/ HTTP/1.1" 400 31
"POST /accounts/login/ HTTP/1.1" 400 31
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/otp/ HTTP/1.1" 200 618
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/otp/ HTTP/1.1" 200 618
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/otp/ HTTP/1.1" 200 618
"OPTIONS /accounts/login/ HTTP/1.1" 200 0
"POST /accounts/login/ HTTP/1.1" 201 117
"OPTIONS /accounts/otp/ HTTP/1.1" 200 0
"POST /accounts/otp/ HTTP/1.1" 200 618
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/otp/ HTTP/1.1" 200 618
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/otp/ HTTP/1.1" 200 618
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/otp/ HTTP/1.1" 200 618
Bad Request: /accounts/login/
Bad Request: /accounts/login/
"POST /accounts/login/ HTTP/1.1" 400 31
"POST /accounts/login/ HTTP/1.1" 400 31
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/otp/ HTTP/1.1" 200 618
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/otp/ HTTP/1.1" 200 618
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/otp/ HTTP/1.1" 200 618
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/otp/ HTTP/1.1" 200 618
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/otp/ HTTP/1.1" 200 618
"OPTIONS /accounts/register/eddc9ee1-f3f9-4577-8c53-7553b5cced47/ HTTP/1.1" 200 0
Not Found: /accounts/register/eddc9ee1-f3f9-4577-8c53-7553b5cced47/
Not Found: /accounts/register/eddc9ee1-f3f9-4577-8c53-7553b5cced47/
"PUT /accounts/register/eddc9ee1-f3f9-4577-8c53-7553b5cced47/ HTTP/1.1" 404 23
"PUT /accounts/register/eddc9ee1-f3f9-4577-8c53-7553b5cced47/ HTTP/1.1" 404 23
- Broken pipe from ('162.142.125.220', 36190)

Not Found: /
Not Found: /
"GET / HTTP/1.1" 404 2930
"GET / HTTP/1.1" 404 2930
- Broken pipe from ('162.142.125.220', 58574)

Not Found: /
Not Found: /
"GET / HTTP/1.1" 404 2930
"GET / HTTP/1.1" 404 2930
code 505, message Invalid HTTP version (2.0)
"PRI * HTTP/2.0" 505 -
"PRI * HTTP/2.0" 505 -
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/otp/ HTTP/1.1" 200 618
"OPTIONS /accounts/register/eddc9ee1-f3f9-4577-8c53-7553b5cced47//profileid/ HTTP/1.1" 200 0
Not Found: /accounts/register/eddc9ee1-f3f9-4577-8c53-7553b5cced47//profileid/
Not Found: /accounts/register/eddc9ee1-f3f9-4577-8c53-7553b5cced47//profileid/
"PUT /accounts/register/eddc9ee1-f3f9-4577-8c53-7553b5cced47//profileid/ HTTP/1.1" 404 6080
"PUT /accounts/register/eddc9ee1-f3f9-4577-8c53-7553b5cced47//profileid/ HTTP/1.1" 404 6080
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/otp/ HTTP/1.1" 200 618
"OPTIONS /accounts/register/eddc9ee1-f3f9-4577-8c53-7553b5cced47/6ad526eb-316f-4b99-b52d-d87a623ff101/ HTTP/1.1" 200 0
Not Found: /accounts/register/eddc9ee1-f3f9-4577-8c53-7553b5cced47/6ad526eb-316f-4b99-b52d-d87a623ff101/
Not Found: /accounts/register/eddc9ee1-f3f9-4577-8c53-7553b5cced47/6ad526eb-316f-4b99-b52d-d87a623ff101/
"PUT /accounts/register/eddc9ee1-f3f9-4577-8c53-7553b5cced47/6ad526eb-316f-4b99-b52d-d87a623ff101/ HTTP/1.1" 404 6158
"PUT /accounts/register/eddc9ee1-f3f9-4577-8c53-7553b5cced47/6ad526eb-316f-4b99-b52d-d87a623ff101/ HTTP/1.1" 404 6158
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/otp/ HTTP/1.1" 200 618
"OPTIONS /accounts/register/6ad526eb-316f-4b99-b52d-d87a623ff101/ HTTP/1.1" 200 0
"PUT /accounts/register/6ad526eb-316f-4b99-b52d-d87a623ff101/ HTTP/1.1" 201 157
"PUT /accounts/register/6ad526eb-316f-4b99-b52d-d87a623ff101/ HTTP/1.1" 201 162
Not Found: /
Not Found: /
"GET / HTTP/1.1" 404 2930
"GET / HTTP/1.1" 404 2930
Not Found: /favicon.ico
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2981
"GET /favicon.ico HTTP/1.1" 404 2981
Performing system checks...

System check identified no issues (0 silenced).
June 23, 2022 - 06:30:45
Django version 4.0.5, using settings 'core.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
{'email': 'jashwanth@digitalgreen.org', 'user_otp': '309581', 'otp_count': 1, 'updation_time': datetime.datetime(2022, 6, 23, 6, 30, 45, 367482)}
{'email': 'jashwanth@digitalgreen.org', 'user_otp': '076911', 'otp_count': 1, 'updation_time': datetime.datetime(2022, 6, 23, 6, 30, 45, 367482)}
{'email': 'jashwanth@digitalgreen.org', 'user_otp': '447983', 'otp_count': 1, 'updation_time': datetime.datetime(2022, 6, 23, 6, 30, 45, 367482)}
{'email': 'jashwanth@digitalgreen.org', 'user_otp': '447279', 'otp_count': 1, 'updation_time': datetime.datetime(2022, 6, 23, 6, 30, 45, 367482)}
{'email': 'jashwanth@digitalgreen.org', 'user_otp': '094352', 'otp_count': 1, 'updation_time': datetime.datetime(2022, 6, 23, 6, 30, 45, 367482)}
{'email': 'jashwanth@digitalgreen.org', 'user_otp': '716171', 'otp_count': 1, 'updation_time': datetime.datetime(2022, 6, 23, 6, 30, 45, 367482)}
{'email': 'jashwanth@digitalgreen.org', 'user_otp': '931552', 'otp_count': 1, 'updation_time': datetime.datetime(2022, 6, 23, 6, 30, 45, 367482)}
{'email': 'jashwanth@digitalgreen.org', 'user_otp': '311375', 'otp_count': 1, 'updation_time': datetime.datetime(2022, 6, 23, 6, 30, 45, 367482)}
{'email': 'jashwanth@digitalgreen.org', 'user_otp': '582197', 'otp_count': 1, 'updation_time': datetime.datetime(2022, 6, 23, 6, 30, 45, 367482)}
{'email': 'jashwanth@digitalgreen.org', 'user_otp': '011741', 'otp_count': 1, 'updation_time': datetime.datetime(2022, 6, 23, 6, 30, 45, 367482)}
{'email': 'jashwanth@digitalgreen.org', 'user_otp': '052089', 'otp_count': 1, 'updation_time': datetime.datetime(2022, 6, 23, 6, 30, 45, 367482)}
{'email': 'jashwanth@digitalgreen.org', 'user_otp': '878862', 'otp_count': 1, 'updation_time': datetime.datetime(2022, 6, 23, 6, 30, 45, 367482)}
{'email': 'jashwanth@digitalgreen.org', 'user_otp': '863216', 'otp_count': 1, 'updation_time': datetime.datetime(2022, 6, 23, 6, 30, 45, 367482)}
{'email': 'jashwanth@digitalgreen.org', 'user_otp': '614363', 'otp_count': 1, 'updation_time': datetime.datetime(2022, 6, 23, 6, 30, 45, 367482)}
{'email': 'jashwanth@digitalgreen.org', 'user_otp': '884876', 'otp_count': 1, 'updation_time': datetime.datetime(2022, 6, 23, 6, 30, 45, 367482)}
{'email': 'jashwanth@digitalgreen.org', 'user_otp': '383258', 'otp_count': 1, 'updation_time': datetime.datetime(2022, 6, 23, 6, 30, 45, 367482)}
{'email': 'jashwanth@digitalgreen.org', 'user_otp': '560575', 'otp_count': 1, 'updation_time': datetime.datetime(2022, 6, 23, 6, 30, 45, 367482)}
{'email': 'jashwanth@digitalgreen.org', 'user_otp': '176569', 'otp_count': 1, 'updation_time': datetime.datetime(2022, 6, 23, 6, 30, 45, 367482)}
{'email': 'jashwanth@digitalgreen.org', 'user_otp': '947851', 'otp_count': 1, 'updation_time': datetime.datetime(2022, 6, 23, 6, 30, 45, 367482)}
{'email': 'jashwanth@digitalgreen.org', 'user_otp': '584752', 'otp_count': 1, 'updation_time': datetime.datetime(2022, 6, 23, 6, 30, 45, 367482)}
{'email': 'jashwanth@digitalgreen.org', 'user_otp': '076228', 'otp_count': 1, 'updation_time': datetime.datetime(2022, 6, 23, 6, 30, 45, 367482)}
{'email': 'jashwanth@digitalgreen.org', 'user_otp': '413572', 'otp_count': 1, 'updation_time': datetime.datetime(2022, 6, 23, 6, 30, 45, 367482)}
{'email': 'jashwanth@digitalgreen.org', 'user_otp': '295018', 'otp_count': 1, 'updation_time': datetime.datetime(2022, 6, 23, 6, 30, 45, 367482)}
{'email': 'jashwanth@digitalgreen.org', 'user_otp': '815261', 'otp_count': 1, 'updation_time': datetime.datetime(2022, 6, 23, 6, 30, 45, 367482)}
{'email': 'jashwanth@digitalgreen.org', 'user_otp': '722207', 'otp_count': 1, 'updation_time': datetime.datetime(2022, 6, 23, 6, 30, 45, 367482)}
{'email': 'jashwanth@digitalgreen.org', 'user_otp': '311010', 'otp_count': 1, 'updation_time': datetime.datetime(2022, 6, 23, 6, 30, 45, 367482)}
{'email': 'jashwanth@digitalgreen.org', 'user_otp': '465889', 'otp_count': 1, 'updation_time': datetime.datetime(2022, 6, 23, 6, 30, 45, 367482)}
{'email': 'jashwanth@digitalgreen.org', 'user_otp': '513180', 'otp_count': 1, 'updation_time': datetime.datetime(2022, 6, 23, 6, 30, 45, 367482)}
{'email': 'jashwanth@digitalgreen.org', 'user_otp': '994112', 'otp_count': 1, 'updation_time': datetime.datetime(2022, 6, 23, 6, 30, 45, 367482)}
{'email': 'jashwanth@digitalgreen.org', 'user_otp': '852420', 'otp_count': 1, 'updation_time': datetime.datetime(2022, 6, 23, 6, 30, 45, 367482)}
/usr/bin/env: ‘python’: No such file or directory
/usr/bin/env: ‘python’: No such file or directory
Traceback (most recent call last):
  File "/home/ubuntu/datahub-api/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/datahub-api/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/datahub-api/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
Traceback (most recent call last):
  File "/home/ubuntu/datahub-api/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/datahub-api/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/datahub-api/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
Traceback (most recent call last):
  File "/home/ubuntu/datahub-api/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/datahub-api/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/datahub-api/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
Traceback (most recent call last):
  File "/home/ubuntu/datahub-api/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/datahub-api/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/datahub-api/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
Traceback (most recent call last):
  File "/home/ubuntu/datahub-api/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/datahub-api/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/datahub-api/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
Watching for file changes with StatReloader
Bad Request: /accounts/register/
Bad Request: /accounts/register/
"POST /accounts/register/ HTTP/1.1" 400 50
"POST /accounts/register/ HTTP/1.1" 400 50
code 400, message Bad request version ('\x04/©´ïWg_û¼\x8a(\x07Ó')
You're accessing the development server over HTTPS, but it only supports HTTP.

You're accessing the development server over HTTPS, but it only supports HTTP.

code 400, message Bad request version ('\x00\x1b\x00\x00\x18datahubtest.farmstack.co\x00\x17\x00\x00ÿ\x01\x00\x01\x00\x00')
You're accessing the development server over HTTPS, but it only supports HTTP.

You're accessing the development server over HTTPS, but it only supports HTTP.

code 400, message Bad request version ('\x00\x1b\x00\x00\x18datahubtest.farmstack.co\x00\x17\x00\x00ÿ\x01\x00\x01\x00\x00')
You're accessing the development server over HTTPS, but it only supports HTTP.

You're accessing the development server over HTTPS, but it only supports HTTP.

code 400, message Bad request version ('ÚÚ\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x01\x93')
You're accessing the development server over HTTPS, but it only supports HTTP.

You're accessing the development server over HTTPS, but it only supports HTTP.

code 400, message Bad request version ('\x9a\x9a\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x01\x93')
You're accessing the development server over HTTPS, but it only supports HTTP.

You're accessing the development server over HTTPS, but it only supports HTTP.

code 400, message Bad request version ('\x00\x1b\x00\x00\x18datahubtest.farmstack.co\x00\x17\x00\x00ÿ\x01\x00\x01\x00\x00')
You're accessing the development server over HTTPS, but it only supports HTTP.

You're accessing the development server over HTTPS, but it only supports HTTP.

Not Found: /
Not Found: /
"GET / HTTP/1.1" 404 2942
"GET / HTTP/1.1" 404 2942
Not Found: /favicon.ico
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2993
"GET /favicon.ico HTTP/1.1" 404 2993
"GET /datahub/participant HTTP/1.1" 301 0
/home/ubuntu/datahub-api/.venv/lib/python3.10/site-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'datahub.models.UserOrganizationMap'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
"GET /datahub/participant/ HTTP/1.1" 200 12821
"GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
"GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
"GET /static/rest_framework/css/default.css HTTP/1.1" 200 1152
"GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
"GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
"GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
"GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
"GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
"GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
"GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
"GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
Bad Request: /datahub/organization/
Bad Request: /datahub/organization/
"POST /datahub/organization/ HTTP/1.1" 400 84
"POST /datahub/organization/ HTTP/1.1" 400 84
Method Not Allowed: /datahub/organization/
Method Not Allowed: /datahub/organization/
"GET /datahub/organization/ HTTP/1.1" 405 9599
"GET /datahub/organization/ HTTP/1.1" 405 9599
"GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
"GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
"GET /static/rest_framework/css/default.css HTTP/1.1" 200 1152
"GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
"GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
"GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
"GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
"GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
"GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
"POST /datahub/organization/ HTTP/1.1" 201 572
Bad Request: /datahub/organization/
Bad Request: /datahub/organization/
"POST /datahub/organization/ HTTP/1.1" 400 84
"POST /datahub/organization/ HTTP/1.1" 400 84
Bad Request: /datahub/organization/
Bad Request: /datahub/organization/
"POST /datahub/organization/ HTTP/1.1" 400 66
"POST /datahub/organization/ HTTP/1.1" 400 66
Method Not Allowed: /datahub/organization/
Method Not Allowed: /datahub/organization/
"GET /datahub/organization/ HTTP/1.1" 405 9599
"GET /datahub/organization/ HTTP/1.1" 405 9599
"GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
"GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
"GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
"GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
"GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
"GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
"GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
"GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
"POST /datahub/organization/ HTTP/1.1" 201 585
Watching for file changes with StatReloader
Bad Request: /accounts/register/
Bad Request: /accounts/register/
"POST /accounts/register/ HTTP/1.1" 400 50
"POST /accounts/register/ HTTP/1.1" 400 50
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/otp/ HTTP/1.1" 200 618
"PUT /accounts/register/6ad526eb-316f-4b99-b52d-d87a623ff101/ HTTP/1.1" 201 158
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/otp/ HTTP/1.1" 200 618
"PUT /accounts/register/6ad526eb-316f-4b99-b52d-d87a623ff101/ HTTP/1.1" 201 158
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/otp/ HTTP/1.1" 200 618
"PUT /accounts/register/6ad526eb-316f-4b99-b52d-d87a623ff101/ HTTP/1.1" 201 158
"POST /accounts/login/ HTTP/1.1" 201 117
Unauthorized: /accounts/otp/
Unauthorized: /accounts/otp/
"POST /accounts/otp/ HTTP/1.1" 401 57
"POST /accounts/otp/ HTTP/1.1" 401 57
"POST /accounts/otp/ HTTP/1.1" 200 618
"PUT /accounts/register/6ad526eb-316f-4b99-b52d-d87a623ff101/ HTTP/1.1" 201 158
/home/ubuntu/datahub-api/core/settings.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
June 23, 2022 - 12:20:15
Django version 4.0.5, using settings 'core.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
{'email': 'jashwanth@digitalgreen.org', 'user_otp': '796405', 'otp_count': 1, 'updation_time': datetime.datetime(2022, 6, 23, 12, 20, 15, 9720)}
{'email': 'jashwanth@digitalgreen.org', 'user_otp': '881128', 'otp_count': 1, 'updation_time': datetime.datetime(2022, 6, 23, 12, 20, 15, 9720)}
{'email': 'jashwanth@digitalgreen.org', 'user_otp': '279788', 'otp_count': 1, 'updation_time': datetime.datetime(2022, 6, 23, 12, 20, 15, 9720)}
{'email': 'jashwanth@digitalgreen.org', 'user_otp': '166905', 'otp_count': 1, 'updation_time': datetime.datetime(2022, 6, 23, 12, 20, 15, 9720)}
Watching for file changes with StatReloader
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/otp/ HTTP/1.1" 200 618
"PUT /accounts/register/6ad526eb-316f-4b99-b52d-d87a623ff101/ HTTP/1.1" 201 156
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/otp/ HTTP/1.1" 200 618
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/otp/ HTTP/1.1" 200 618
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/otp/ HTTP/1.1" 200 618
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/otp/ HTTP/1.1" 200 618
"PUT /accounts/register/6ad526eb-316f-4b99-b52d-d87a623ff101/ HTTP/1.1" 201 158
Watching for file changes with StatReloader
"POST /accounts/login/ HTTP/1.1" 201 117
Bad Request: /accounts/register/
Bad Request: /accounts/register/
"POST /accounts/register/ HTTP/1.1" 400 50
"POST /accounts/register/ HTTP/1.1" 400 50
"POST /accounts/otp/ HTTP/1.1" 200 618
"PUT /accounts/register/6ad526eb-316f-4b99-b52d-d87a623ff101/ HTTP/1.1" 201 139
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/otp/ HTTP/1.1" 200 618
"PUT /accounts/register/6ad526eb-316f-4b99-b52d-d87a623ff101/ HTTP/1.1" 201 138
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/otp/ HTTP/1.1" 200 618
"PUT /accounts/register/6ad526eb-316f-4b99-b52d-d87a623ff101/ HTTP/1.1" 201 143
"POST /accounts/login/ HTTP/1.1" 201 117
"POST /accounts/otp/ HTTP/1.1" 200 618
"PUT /accounts/register/6ad526eb-316f-4b99-b52d-d87a623ff101/ HTTP/1.1" 201 155
"POST /datahub/organization/ HTTP/1.1" 201 599
